def main():
    age = int(input("Please enter your age: "))
    restHR = int(input("Please enter your resting heart rate: "))
    maxHR = round(float(208-7/10 * age), 2)
    reserveHR = round((maxHR - restHR), 1)
    print("========================================")
    print("Your heart rate reserve is:", reserveHR, "bpm")
    print("Here is a breakdown of your training zones:")
    Zone1min = round(float(restHR + (reserveHR*5/10)), 2)
    Zone1max = round(float(restHR + (reserveHR*6/10-1/100)), 2)
    print("Zone 1:", Zone1min, "to", Zone1max, "bpm")
    Zone2min = round(float(restHR + (reserveHR*6/10)), 2)
    Zone2max = round(float(restHR + (reserveHR*7/10-1/100)), 2)
    print("Zone 2:", Zone2min, "to", Zone2max, "bpm")
    Zone3min = round(float(restHR + (reserveHR*7/10)), 2)
    Zone3max = round(float(restHR + (reserveHR*8/10-1/100)), 2)
    print("Zone 3:", Zone3min, "to", Zone3max, "bpm")
    Zone4min = round(float(restHR + (reserveHR*8/10)), 2)
    Zone4max = round(float(restHR + (reserveHR*93/100-1/100)), 2)
    print("Zone 4:", Zone4min, "to", Zone4max, "bpm")
    Zone5min = round(float(restHR + (reserveHR*93/100)), 2)
    Zone5max = round(float(restHR + (reserveHR*10/10)), 2)
    print("Zone 5:", Zone5min, "to", Zone5max, "bpm")


main()
